version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8002:8000"
    volumes:
      - ./models:/models
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "8502:8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - ./frontend/assets:/app/assets
      - ./models:/app/models
    networks:
      - app_network

  training:
    build: ./training
    volumes:
      - ./training_data:/data
      - ./models:/models
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app_network
    restart: unless-stopped
    command: >
      bash -c "
        echo '⏳ Attente de MLflow...';
        sleep 10;
        python train.py --data /data/data.yaml --img 416 --batch 4 --mlflow-uri http://mlflow:5000;
      "

networks:
  app_network:
    driver: bridge
